### ISSUE TITLE
how to call the lock/unlock service

### ISSUE THREAD

**Issue by JamieP83** [Cyr-ius/hass-audiconnect#13]
hey all,
trying to add a script but not sure if i need to audi my audi SPIN?

this doesnt seem to work?

```
audi_service_lock:
  sequence:
    - service: audiconnect.execute_vehicle_action
      data:
        vin: !secret audisq5vin
        action: "lock"
```
