### ISSUE TITLE
Lock / unlock service not working?

### ISSUE THREAD

**Issue by JamieP83** [cyr-ius/hass-audiconnect#80]
Hey all,

Firstly, thanks so much for the work gone into this!

Im trying to do 3 basic things:
- lock
- unlock
- refresh
however, no luck with any!

I tried all these for lock/unlock but none worked? any thoughts?
my car senors show up great, so the integration is working!!
```

service: audiconnect.turn_on_action
data:
  vin: 05b556718de7381c53xxxxxxbc5
  action: lock

service: audiconnect.turn_on_action
data:
  vin: 05b556718de7381c53xxxxxxbc5
  action: unlock


service: audiconnect.turn_off_action
data:
  vin: 05b556718de7381c53xxxxxxbc5
  action: unlock

service: audiconnect.turn_off_action
data:
  vin: 05b556718de7381c53xxxxxxbc5
  action: lock
  
```
  
  also, should "turn off" and "lock" then unlock the car?
![image](https://github.com/cyr-ius/hass-audiconnect/assets/48566948/d834cfad-1cbf-4db8-893f-210046db829a)

![image](https://github.com/cyr-ius/hass-audiconnect/assets/48566948/ef8bf4ab-3ee1-4fcc-a1e2-b08822cec3f4)
